def filee(a,name,choice,d,t_price,discount_p,quantity_p):
    file=open(a+".txt","w")
    file.write(str("\n"))
    file.write(str("***INVOICE***"))
    file.write(str("\n"))
    file.write(str("Invoice No=" + a))
    file.write(str("\n"))
    file.write(str("Customer Name=" + name))
    file.write(str("\n"))
    file.write(str("Customer's Product=" + choice))
    file.write(str("\n"))
    file.write(str("Purchased Date=" + d))
    file.write(str("\n"))
    file.write("Product Price=" + str(t_price))
    file.write(str("\n"))
    file.write("Discount Amount=" + str(discount_p))
    file.write(str("\n"))
    file.write("Product Quantity=" + str(quantity_p))
    file.write(str("\n"))
    file.write(str("**************"))
    file.close()
    
    print("********INVOICE********")
    print("Invoice number: ",a)
    print("Date of purchase: ",d)
    print("Customer's Name: ",name)
    print("Purchased Product: ",choice)
    print("Product Quantity: ",quantity_p)
    print("Discount Amount: ",discount_p)
    print("Total amount: ",t_price)
    print("***********************") 
